sudo: false
language: python
env:
- PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin PYTHONPATH=${HOME}/gcloud/google-cloud-sdk/platform/google_appengine
before_install:
- openssl aes-256-cbc -K $encrypted_7014fa6351c8_key -iv $encrypted_7014fa6351c8_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib
install:
- pip install -r requirements.txt -t lib/
script:
- echo "No script to run"
deploy:
    skip_cleanup: true
    provider: gae
    keyfile: client-secret.json
    project: continuous-deployment-python
    default: true
    on:
      all_branches: false
